### ISSUE TITLE
error

### ISSUE THREAD

**Issue by mlodylew1990** [cgtinker/BlendArMocap#106]
i have this error:

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\Adrian\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\BlendArMocap-main\__init__.py", line 40, in <module>
    reload_modules()
  File "C:\Users\Adrian\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\BlendArMocap-main\__init__.py", line 36, in reload_modules
    cgt_imports.manage_imports()
  File "C:\Users\Adrian\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\BlendArMocap-main\src\cgt_imports.py", line 100, in manage_imports
    import_module(module)
  File "C:\Users\Adrian\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\BlendArMocap-main\src\cgt_imports.py", line 52, in import_module
    importlib.import_module(f"{PACKAGE_NAME}{module}")
  File "C:\Program Files\Blender Foundation\Blender 3.3\3.3\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\Adrian\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\BlendArMocap-main\src\cgt_detection\detector_interface.py", line 20, in <module>
    from mediapipe import solutions
ModuleNotFoundError: No module named 'mediapipe'

**Comment by underdoeg** [comment]
you probably need to install the dependencies. the script is looking for mediapipe but cant find it

**Comment by cgtinker** [comment]
I'm about to release an update next week, you can give it a try by downloading the main branch. if the issue persist, please refer to #131
