### ISSUE TITLE
Can't initialize detector on Linux

### ISSUE THREAD

**Issue by Alexia-AT-Digitecnology** [cgtinker/BlendArMocap#120]
**OS:** ArchLinux latest
**Blender Version:** 3.4.1

I have the dependencies installed, I applied Rigify and BlendARMocap plugins and when I press "Start Detection" button it throws an error:

```
Python: Exception ignored in: <function RealtimeDetector.__del__ at 0x7facd27d0d30>
Traceback (most recent call last):
  File "/home/alexiarc/.config/blender/3.4/scripts/addons/BlendArMocap-main/src/cgt_detection/detector_interface.py", line 121, in __del__
    self.listener.detach(self.observer)
AttributeError: 'NoneType' object has no attribute 'detach'
DEL STREAM
Traceback (most recent call last):
  File "/home/alexiarc/.config/blender/3.4/scripts/addons/BlendArMocap-main/src/cgt_blender/interface/ui_operators.py", line 120, in execute
    self.detection_handler.init_detector(camera_index, dimensions, backend, frame_start, key_step, 0)
  File "/home/alexiarc/.config/blender/3.4/scripts/addons/BlendArMocap-main/src/main.py", line 121, in init_detector
    raise IOError("Initializing Detector failed.")
OSError: Initializing Detector failed.
```
Here is my blender system info: [system-info.txt](https://github.com/cgtinker/BlendArMocap/files/10548356/system-info.txt)

**Comment by cgtinker** [comment]
Can you try downloading BlendArMocap from the main branch and let me know it the error persists?

**Comment by cgtinker** [comment]
please refer to #129
