### ISSUE TITLE
Traceback error when activating plugin

### ISSUE THREAD

**Issue by kyaustad** [cgtinker/BlendArMocap#13]
```
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\MYUSERNAME\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\BlendArMocap-release\__init__.py", line 41, in <module>
    from utils import log
ImportError: cannot import name 'log' from 'utils' (C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\startup\bl_ui\utils.py)
```

This error pops up upon trying to check the box to activate the plugin. Both downloading from Github and Gumroad. Windows 10. Run as admin.

**Comment by cgtinker** [comment]
Try the updated version from the main branch, should be fixed now
