### ISSUE TITLE
Cannot initialize type "Image"

### ISSUE THREAD

**Issue by Desagiato** [cgtinker/BlendArMocap#137]
Python: Traceback (most recent call last):
  File "/root/.config/blender/3.0/scripts/addons/BlendArMocap-main/src/cgt_mediapipe/cgt_mp_detection_operator.py", line 110, in execute
    self.node_chain = self.get_chain(stream)
  File "/root/.config/blender/3.0/scripts/addons/BlendArMocap-main/src/cgt_mediapipe/cgt_mp_detection_operator.py", line 21, in get_chain
    from .cgt_mp_core import mp_hand_detector, mp_face_detector, mp_pose_detector, mp_holistic_detector
  File "/root/.config/blender/3.0/scripts/addons/BlendArMocap-main/src/cgt_mediapipe/cgt_mp_core/mp_hand_detector.py", line 1, in <module>
    import mediapipe as mp
  File "/usr/local/lib/python3.10/dist-packages/mediapipe/__init__.py", line 15, in <module>
    from mediapipe.python import *
  File "/usr/local/lib/python3.10/dist-packages/mediapipe/python/__init__.py", line 17, in <module>
    from mediapipe.python._framework_bindings import resource_util
ImportError: generic_type: cannot initialize type "Image": an object with that name is already defined

location: <unknown location>:-1

**Comment by cgtinker** [comment]
guess that's part of #138
