### ISSUE TITLE
Cant detect. Python issue.

### ISSUE THREAD

**Issue by BennyVerasRJC** [cgtinker/BlendArMocap#141]
At start the detection this message apprears as an error.

Python: Traceback (most recent call last):
  File "C:\Users\Benny Veras\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlendArMocap-main\src\cgt_mediapipe\cgt_mp_detection_operator.py", line 109, in execute
    stream = self.get_stream()
  File "C:\Users\Benny Veras\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlendArMocap-main\src\cgt_mediapipe\cgt_mp_detection_operator.py", line 66, in get_stream
    from .cgt_mp_core import cv_stream
  File "C:\Users\Benny Veras\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlendArMocap-main\src\cgt_mediapipe\cgt_mp_core\cv_stream.py", line 4, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

**Comment by fengge111111** [comment]
Why is the pose character I generated tilted, cgt_hip_center does not move, and the action is weird

**Comment by cgtinker** [comment]
hey, did you install the dependencies as admin on windows?
It seems like either there is a package conflict with opencv, opencv is not installed or opencv is corrupted.

Please [gather infomation](https://cgtinker.github.io/BlendArMocap/installation/manual_dependency_installation.html#gather-information) then open you system console and run the cmd:
`"blenders python exe" -m pip freeze`

if you installed them to the local user:
`python3 -m pip freeze`

if the text message is huge, please create file and upload it
`"python path" -m pip freeze > info.txt`

let me know the output.
