### ISSUE TITLE
Linux can't open camera by index cap_v4l

### ISSUE THREAD

**Issue by arpu** [cgtinker/BlendArMocap#15]
Hi, get this on fedora 

```
[ WARN:0@133.029] global /io/opencv/modules/videoio/src/cap_v4l.cpp (889) open VIDEOIO(V4L2:/dev/video1): can't open camera by index
Python: Traceback (most recent call last):
  File "/root/.config/blender/3.1/scripts/addons/BlendArMocap-main/_blender/interface/stream_detection_operator.py", line 47, in execute
    self.init_detector(detection_type)
  File "/root/.config/blender/3.1/scripts/addons/BlendArMocap-main/_blender/interface/stream_detection_operator.py", line 69, in init_detector
    self.tracking_handler.stream = stream.Webcam(camera_index=camera_index)
  File "/root/.config/blender/3.1/scripts/addons/BlendArMocap-main/utils/open_cv/stream.py", line 14, in __init__
    raise IOError("Cannot open webcam")
OSError: Cannot open webcam

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "/root/.config/blender/3.1/scripts/addons/BlendArMocap-main/_blender/interface/stream_detection_operator.py", line 47, in execute
    self.init_detector(detection_type)
  File "/root/.config/blender/3.1/scripts/addons/BlendArMocap-main/_blender/interface/stream_detection_operator.py", line 69, in init_detector
    self.tracking_handler.stream = stream.Webcam(camera_index=camera_index)
  File "/root/.config/blender/3.1/scripts/addons/BlendArMocap-main/utils/open_cv/stream.py", line 14, in __init__
    raise IOError("Cannot open webcam")
OSError: Cannot open webcam

location: <unknown location>:-1
```

**Comment by arpu** [comment]
wrong video1 was used video0 works
