### ISSUE TITLE
MediaPipe crash on fedora

### ISSUE THREAD

**Issue by arpu** [cgtinker/BlendArMocap#16]
hi after starting hand detection blender crash with this infos

```
sudo ./blender
Read prefs: /root/.config/blender/3.1/config/userpref.blend
2022-02-11 21:23:42,065 - app - DEBUG - REGISTERING BLENDARMOCAP (ui_registration.py:40)
2022-02-11 21:23:42,065 - app - DEBUG - <class '_blender.interface.ui_preferences.PREFERENCES_OT_install_dependencies_button'> (ui_registration.py:43)
2022-02-11 21:23:42,065 - app - DEBUG - <class '_blender.interface.ui_preferences.BLENDARMOCAP_preferences'> (ui_registration.py:43)
2022-02-11 21:23:42,066 - app - DEBUG - <class '_blender.interface.ui_panels.UI_PT_warning_panel'> (ui_registration.py:43)
2022-02-11 21:23:42,066 - app - DEBUG - TRY ACCESS INSTALLED DEPENDENCIES (ui_registration.py:47)
2022-02-11 21:23:42,066 - app - DEBUG - Dependency(module='mediapipe', package=None, name=None) (ui_registration.py:49)
2022-02-11 21:23:42,710 - app - DEBUG - Dependency(module='opencv-python', package=None, name='cv2') (ui_registration.py:49)
2022-02-11 21:23:42,710 - app - INFO - REGISTER BLENDARMOCAP INTERFACE (ui_registration.py:62)
2022-02-11 21:23:42,710 - app - DEBUG - <class '_blender.interface.properties.MyProperties'> (ui_registration.py:64)
2022-02-11 21:23:42,710 - app - DEBUG - <class '_blender.interface.ui_panels.UI_transfer_anim_button'> (ui_registration.py:64)
2022-02-11 21:23:42,710 - app - DEBUG - <class '_blender.interface.stream_detection_operator.WM_modal_detection_operator'> (ui_registration.py:64)
2022-02-11 21:23:42,710 - app - DEBUG - <class '_blender.interface.ui_panels.UI_PT_main_panel'> (ui_registration.py:64)
2022-02-11 21:24:04,483 - app - INFO - RUNNING MP AS TIMER DETECTION MODAL (stream_detection_operator.py:35)
2022-02-11 21:24:04,484 - app - INFO - INITIALIZING HAND DETECTION (stream_detection_operator.py:59)
2022-02-11 21:24:05,628 - app - DEBUG - OBSERVER ATTACHED FROM UPDATE LISTENER (events.py:15)
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Writing: /tmp/blender.crash.txt
[1]    44879 segmentation fault  sudo ./blender
❯ cat /tmp/blender.crash.txt
# Blender 3.1.0, Commit date: 2022-02-09 17:06, Hash d1202bd641ca
bpy.data.window_managers["WinMan"].addon_search = "moc"  # Property
bpy.context.scene.m_cgtinker_mediapipe.key_frame_step = 1  # Property

# backtrace
./blender(BLI_system_backtrace+0x20) [0xb32b0a0]
./blender() [0x112feda]
/lib64/libc.so.6(+0x42750) [0x7fb480429750]
./blender() [0x15cf089]
/home/arpu/Downloads/blender-3.1.0-beta+v31.d1202bd641ca-linux.x86_64-release/3.1/python/lib/python3.10/site-packages/mediapipe/python/_framework_bindings.cpython-310-x86_64-linux-gnu.so(_ZN6tflite8Subgraph11CleanupNodeEi+0x4d) [0x7fb44175999d]
/home/arpu/Downloads/blender-3.1.0-beta+v31.d1202bd641ca-linux.x86_64-release/3.1/python/lib/python3.10/site-packages/mediapipe/python/_framework_bindings.cpython-310-x86_64-linux-gnu.so(_ZN6tflite8SubgraphD1Ev+0x4f) [0x7fb441759a1f]
/home/arpu/Downloads/blender-3.1.0-beta+v31.d1202bd641ca-linux.x86_64-release/3.1/python/lib/python3.10/site-packages/mediapipe/python/_framework_bindings.cpython-310-x86_64-linux-gnu.so(_ZN6tflite8SubgraphD0Ev+0x12) [0x7fb441759c82]
/home/arpu/Downloads/blender-3.1.0-beta+v31.d1202bd641ca-linux.x86_64-release/3.1/python/lib/python3.10/site-packages/mediapipe/python/_framework_bindings.cpython-310-x86_64-linux-gnu.so(_ZN6tflite11InterpreterD1Ev+0x1ef) [0x7fb44176433f]
/home/arpu/Downloads/blender-3.1.0-beta+v31.d1202bd641ca-linux.x86_64-release/3.1/python/lib/python3.10/site-packages/mediapipe/python/_framework_bindings.cpython-310-x86_64-linux-gnu.so(_ZN9mediapipe4api226InferenceCalculatorCpuImpl5CloseEPNS_17CalculatorContextE+0x2c) [0x7fb4410ea44c]
/home/arpu/Downloads/blender-3.1.0-beta+v31.d1202bd641ca-linux.x86_64-release/3.1/python/lib/python3.10/site-packages/mediapipe/python/_framework_bindings.cpython-310-x86_64-linux-gnu.so(_ZN9mediapipe14CalculatorNode9CloseNodeERKN4absl12lts_202103246StatusEb+0x919) [0x7fb4417d6dd9]
/home/arpu/Downloads/blender-3.1.0-beta+v31.d1202bd641ca-linux.x86_64-release/3.1/python/lib/python3.10/site-packages/mediapipe/python/_framework_bindings.cpython-310-x86_64-linux-gnu.so(_ZN9mediapipe14CalculatorNode11ProcessNodeEPNS_17CalculatorContextE+0x1de) [0x7fb4417d72fe]
/home/arpu/Downloads/blender-3.1.0-beta+v31.d1202bd641ca-linux.x86_64-release/3.1/python/lib/python3.10/site-packages/mediapipe/python/_framework_bindings.cpython-310-x86_64-linux-gnu.so(_ZN9mediapipe8internal14SchedulerQueue17RunCalculatorNodeEPNS_14CalculatorNodeEPNS_17CalculatorContextE+0xfb) [0x7fb4417d11cb]
/home/arpu/Downloads/blender-3.1.0-beta+v31.d1202bd641ca-linux.x86_64-release/3.1/python/lib/python3.10/site-packages/mediapipe/python/_framework_bindings.cpython-310-x86_64-linux-gnu.so(_ZN9mediapipe8internal14SchedulerQueue11RunNextTaskEv+0x81) [0x7fb4417d1d31]
/home/arpu/Downloads/blender-3.1.0-beta+v31.d1202bd641ca-linux.x86_64-release/3.1/python/lib/python3.10/site-packages/mediapipe/python/_framework_bindings.cpython-310-x86_64-linux-gnu.so(_ZN9mediapipe10ThreadPool9RunWorkerEv+0xc4) [0x7fb44180c014]
/home/arpu/Downloads/blender-3.1.0-beta+v31.d1202bd641ca-linux.x86_64-release/3.1/python/lib/python3.10/site-packages/mediapipe/python/_framework_bindings.cpython-310-x86_64-linux-gnu.so(_ZN9mediapipe10ThreadPool12WorkerThread10ThreadBodyEPv+0x33d) [0x7fb44180c59d]
/lib64/libc.so.6(+0x8db1a) [0x7fb480474b1a]
/lib64/libc.so.6(+0x112650) [0x7fb4804f9650]

# Python backtrace


```

**Comment by sjkillen** [comment]
Also have this error on Ubuntu with Blender 3.3
```
#0  rtree_szind_slab_read (r_slab=<synthetic pointer>, r_szind=<synthetic pointer>, dependent=true, key=327156384, rtree_ctx=0x7fff839b9bb0, rtree=<optimized out>, tsdn=<optimized out>) at include/jemalloc/internal/rtree.h:500
#1  ifree (slow_path=false, tcache=0x7fff839b9d70, ptr=0x138002a0, tsd=<optimized out>) at src/jemalloc.c:2570
#2  je_free_default (ptr=0x138002a0) at src/jemalloc.c:2790
#3  0x00007fffaa3b482d in tflite::Subgraph::CleanupNode(int) () at /home/capybara/blender-git/build_linux_full/bin/3.3/python/lib/python3.10/site-packages/mediapipe/python/_framework_bindings.cpython-310-x86_64-linux-gnu.so
#4  0x00007fffaa3b48af in tflite::Subgraph::~Subgraph() () at /home/capybara/blender-git/build_linux_full/bin/3.3/python/lib/python3.10/site-packages/mediapipe/python/_framework_bindings.cpython-310-x86_64-linux-gnu.so
#5  0x00007fffaa3b4b12 in tflite::Subgraph::~Subgraph() () at /home/capybara/blender-git/build_linux_full/bin/3.3/python/lib/python3.10/site-packages/mediapipe/python/_framework_bindings.cpython-310-x86_64-linux-gnu.so
#6  0x00007fffaa3bf1af in tflite::Interpreter::~Interpreter() () at /home/capybara/blender-git/build_linux_full/bin/3.3/python/lib/python3.10/site-packages/mediapipe/python/_framework_bindings.cpython-310-x86_64-linux-gnu.so
#7  0x00007fffa9dd2cec in mediapipe::api2::InferenceCalculatorCpuImpl::Close(mediapipe::CalculatorContext*) ()
    at /home/capybara/blender-git/build_linux_full/bin/3.3/python/lib/python3.10/site-packages/mediapipe/python/_framework_bindings.cpython-310-x86_64-linux-gnu.so
#8  0x00007fffaa504d29 in mediapipe::CalculatorNode::CloseNode(absl::lts_20210324::Status const&, bool) ()
    at /home/capybara/blender-git/build_linux_full/bin/3.3/python/lib/python3.10/site-packages/mediapipe/python/_framework_bindings.cpython-310-x86_64-linux-gnu.so
#9  0x00007fffaa5051ee in mediapipe::CalculatorNode::ProcessNode(mediapipe::CalculatorContext*) () at /home/capybara/blender-git/build_linux_full/bin/3.3/python/lib/python3.10/site-packages/mediapipe/python/_framework_bindings.cpython-310-x86_64-linux-gnu.so
#10 0x00007fffaa4ff57b in mediapipe::internal::SchedulerQueue::RunCalculatorNode(mediapipe::CalculatorNode*, mediapipe::CalculatorContext*) ()
    at /home/capybara/blender-git/build_linux_full/bin/3.3/python/lib/python3.10/site-packages/mediapipe/python/_framework_bindings.cpython-310-x86_64-linux-gnu.so
#11 0x00007fffaa5000e1 in mediapipe::internal::SchedulerQueue::RunNextTask() () at /home/capybara/blender-git/build_linux_full/bin/3.3/python/lib/python3.10/site-packages/mediapipe/python/_framework_bindings.cpython-310-x86_64-linux-gnu.so
#12 0x00007fffaa538284 in mediapipe::ThreadPool::RunWorker() () at /home/capybara/blender-git/build_linux_full/bin/3.3/python/lib/python3.10/site-packages/mediapipe/python/_framework_bindings.cpython-310-x86_64-linux-gnu.so
#13 0x00007fffaa53880d in mediapipe::ThreadPool::WorkerThread::ThreadBody(void*) () at /home/capybara/blender-git/build_linux_full/bin/3.3/python/lib/python3.10/site-packages/mediapipe/python/_framework_bindings.cpython-310-x86_64-linux-gnu.so
#14 0x00007ffff7ad1947 in start_thread (arg=<optimized out>) at pthread_create.c:435
#15 0x00007ffff7b61a44 in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:100
```
Stack trace indicates that the crash is happening inside tensorflow

**Comment by cgtinker** [comment]
Fedora still isn't officially supported by mediapipe, not really sure if that's fixable. I've worked on a new version, mediapipe also updated by the time and it might be worth to give it a try, but I can imagine the issue persist. Please refer to #129 if you face issues
