### ISSUE TITLE
Linux crash after Linux Mint upgrade 

### ISSUE THREAD

**Issue by bazza2jw** [cgtinker/BlendArMocap#167]
BlendAR worked with Linux Mint 20 but after upgrading to Linux Mint 21 it crashes probably when creating the image window. Both with webcam and file input sources.

GDB traceback below. 

Thread 1 "blender" received signal SIGSEGV, Segmentation fault.
0x00007fff1a605263 in find_atom_pointer () from /home/barry/bin/blender-3.6.4-linux-x64/3.6/python/lib/python3.10/site-packages/cv2/qt/plugins/platforms/../../../../opencv_contrib_python.libs/libxkbcommon-x11-c65ed502.so.0.0.0
(gdb) backtrace
#0  0x00007fff1a605263 in find_atom_pointer () at /home/barry/bin/blender-3.6.4-linux-x64/3.6/python/lib/python3.10/site-packages/cv2/qt/plugins/platforms/../../../../opencv_contrib_python.libs/libxkbcommon-x11-c65ed502.so.0.0.0
#1  0x00007fff1a60548e in atom_intern () at /home/barry/bin/blender-3.6.4-linux-x64/3.6/python/lib/python3.10/site-packages/cv2/qt/plugins/platforms/../../../../opencv_contrib_python.libs/libxkbcommon-x11-c65ed502.so.0.0.0
#2  0x00007fff1a604ff5 in xkb_keymap_new () at /home/barry/bin/blender-3.6.4-linux-x64/3.6/python/lib/python3.10/site-packages/cv2/qt/plugins/platforms/../../../../opencv_contrib_python.libs/libxkbcommon-x11-c65ed502.so.0.0.0
#3  0x00007fff1a602caf in xkb_x11_keymap_new_from_device ()
    at /home/barry/bin/blender-3.6.4-linux-x64/3.6/python/lib/python3.10/site-packages/cv2/qt/plugins/platforms/../../../../opencv_contrib_python.libs/libxkbcommon-x11-c65ed502.so.0.0.0
#4  0x00007fff5be85558 in  () at /home/barry/bin/blender-3.6.4-linux-x64/3.6/python/lib/python3.10/site-packages/cv2/qt/plugins/platforms/../../../../opencv_contrib_python.libs/libQt5XcbQpa-5b2d853e.so.5.15.0
#5  0x00007fff5be802a4 in QtOpenCVPython::QXcbConnection::QXcbConnection(QtOpenCVPython::QXcbNativeInterface*, bool, unsigned int, char const*) ()
    at /home/barry/bin/blender-3.6.4-linux-x64/3.6/python/lib/python3.10/site-packages/cv2/qt/plugins/platforms/../../../../opencv_contrib_python.libs/libQt5XcbQpa-5b2d853e.so.5.15.0
#6  0x00007fff5be82c87 in QtOpenCVPython::QXcbIntegration::QXcbIntegration(QtOpenCVPython::QStringList const&, int&, char**) ()
    at /home/barry/bin/blender-3.6.4-linux-x64/3.6/python/lib/python3.10/site-packages/cv2/qt/plugins/platforms/../../../../opencv_contrib_python.libs/libQt5XcbQpa-5b2d853e.so.5.15.0
#7  0x00007fffa8a1e43f in  () at /home/barry/bin/blender-3.6.4-linux-x64/3.6/python/lib/python3.10/site-packages/cv2/qt/plugins/platforms/libqxcb.so
#8  0x00007fff6bfdfa7c in QtOpenCVPython::QGuiApplicationPrivate::createPlatformIntegration() ()
    at /home/barry/bin/blender-3.6.4-linux-x64/3.6/python/lib/python3.10/site-packages/cv2/../opencv_contrib_python.libs/libQt5Gui-a7aedf18.so.5.15.0
#9  0x00007fff6bfe1020 in QtOpenCVPython::QGuiApplicationPrivate::createEventDispatcher() ()
    at /home/barry/bin/blender-3.6.4-linux-x64/3.6/python/lib/python3.10/site-packages/cv2/../opencv_contrib_python.libs/libQt5Gui-a7aedf18.so.5.15.0
#10 0x00007fff6ba572f6 in QtOpenCVPython::QCoreApplicationPrivate::init() () at /home/barry/bin/blender-3.6.4-linux-x64/3.6/python/lib/python3.10/site-packages/cv2/../opencv_contrib_python.libs/libQt5Core-39545cc7.so.5.15.0
#11 0x00007fff6bfe3a4b in QtOpenCVPython::QGuiApplicationPrivate::init() () at /home/barry/bin/blender-3.6.4-linux-x64/3.6/python/lib/python3.10/site-packages/cv2/../opencv_contrib_python.libs/libQt5Gui-a7aedf18.so.5.15.0
#12 0x00007fff6c8a8979 in QtOpenCVPython::QApplicationPrivate::init() () at /home/barry/bin/blender-3.6.4-linux-x64/3.6/python/lib/python3.10/site-packages/cv2/../opencv_contrib_python.libs/libQt5Widgets-e69d94fb.so.5.15.0
#13 0x00007fff6fd28077 in  () at /home/barry/bin/blender-3.6.4-linux-x64/3.6/python/lib/python3.10/site-packages/cv2/cv2.abi3.so
#14 0x00007fff6fd3427d in  () at /home/barry/bin/blender-3.6.4-linux-x64/3.6/python/lib/python3.10/site-packages/cv2/cv2.abi3.so
#15 0x00007fff6fd222fc in  () at /home/barry/bin/blender-3.6.4-linux-x64/3.6/python/lib/python3.10/site-packages/cv2/cv2.abi3.so
#16 0x00007fff6ecd0ce3 in  () at /home/barry/bin/blender-3.6.4-linux-x64/3.6/python/lib/python3.10/site-packages/cv2/cv2.abi3.so
#17 0x000000000082675e in  ()
#18 0x000000000080135b in _PyObject_MakeTpCall ()
#19 0x000000000086204c in _PyEval_EvalFrameDefault ()
#20 0x000000000085ba12 in  ()
#21 0x000000000085cf43 in _PyEval_EvalFrameDefault ()
#22 0x000000000085ba12 in  ()
#23 0x000000000085cf43 in _PyEval_EvalFrameDefault ()
#24 0x000000000085ba12 in  ()
#25 0x000000000085cf43 in _PyEval_EvalFrameDefault ()
#26 0x000000000085ba12 in  ()
#27 0x0000000001430788 in  ()
#28 0x00000000013f7b6b in  ()
#29 0x0000000000eba20c in  ()
#30 0x0000000000ebb689 in  ()
#31 0x0000000000ebbbbd in  ()
#32 0x0000000000ebc693 in  ()
#33 0x0000000000eb00b0 in  ()
#34 0x000000000070f4ee in  ()
#35 0x00007fffe8668d90 in __libc_start_call_main (main=main@entry=0x70f1b0, argc=argc@entry=1, argv=argv@entry=0x7fffffffde78) at ../sysdeps/nptl/libc_start_call_main.h:58
#36 0x00007fffe8668e40 in __libc_start_main_impl (main=0x70f1b0, argc=1, argv=0x7fffffffde78, init=<optimised out>, fini=<optimised out>, rtld_fini=<optimised out>, stack_end=0x7fffffffde68) at ../csu/libc-start.c:392
#37 0x00000000008a8c1e in  ()

**Comment by PKMpl** [comment]
Ubuntu 23.10 (Haven't tried it on previous releases)

Error when clicking start detection (camera)

> Python: Traceback (most recent call last):
>   File "/home/user/.var/app/org.blender.Blender/config/blender/3.6/scripts/addons/BlendArMocap/src/cgt_mediapipe/cgt_mp_detection_operator.py", line 109, in execute
>     
>   File "/home/user/.var/app/org.blender.Blender/config/blender/3.6/scripts/addons/BlendArMocap/src/cgt_mediapipe/cgt_mp_detection_operator.py", line 90, in get_stream
>     
>   File "/home/user/.var/app/org.blender.Blender/config/blender/3.6/scripts/addons/BlendArMocap/src/cgt_mediapipe/cgt_mp_core/cv_stream.py", line 39, in __init__
>     raise IOError("Cannot open webcam")
> OSError: Cannot open webcam
> 

When using a video file it creates someting and then Blender crashes instantly
