### ISSUE TITLE
Issue while trying to on camera

### ISSUE THREAD

**Issue by TacticalTriggers** [cgtinker/BlendArMocap#184]
Python: Traceback (most recent call last):
  File "/Users/zainimran/Library/Application Support/Blender/4.1/scripts/addons/BlendArMocap-main/src/cgt_mediapipe/cgt_mp_detection_operator.py", line 111, in execute
    stream = self.get_stream()
             ^^^^^^^^^^^^^^^^^
  File "/Users/zainimran/Library/Application Support/Blender/4.1/scripts/addons/BlendArMocap-main/src/cgt_mediapipe/cgt_mp_detection_operator.py", line 91, in get_stream
    stream = cv_stream.Stream(
             ^^^^^^^^^^^^^^^^^
  File "/Users/zainimran/Library/Application Support/Blender/4.1/scripts/addons/BlendArMocap-main/src/cgt_mediapipe/cgt_mp_core/cv_stream.py", line 39, in __init__
    raise IOError("Cannot open webcam")
OSError: Cannot open webcam

Am having issues with opening camera. I am on a mac.

**Comment by vorukanu** [comment]
I had the same issue on windows. 

What solved it for me was using webcam device slot 0 instead of slot 1.
