### ISSUE TITLE
Error when using Mediapipe:  numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by gj1342** [cgtinker/BlendArMocap#185]
**Describe the bug**
Python: Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1232, in _handle_fromlist
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\ACER\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\BlendArMocap\src\cgt_mediapipe\cgt_mp_core\cv_stream.py", line 4, in <module>
    import cv2
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\python\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\python\cv2\__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.2\4.2\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: numpy.core.multiarray failed to import

**To Reproduce**
1. Go to the sidebar and click BlendAR
2. Detect Webcam with 0 slot and 4 value Key Step
3. Target Hands and press start detection

**Expected behavior**
OpenCV will start and detect my hands

**Screenshots**
Always copy the log message from the system console if an error occurs. Do not create screenshots of error messages. If applicable, add screenshots to help explain your problem. 

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Blender VersionL Blender 4.2
 - BlendArMocap Version: 1.6.1

**Comment by WolfgangNS** [comment]
I had the similar issue, only with movie instead of webcam. While I did try some miscellaneous fixes (run as administrator, install opencv-python), ultimately my fix was just to specify the file path. Easy as that. 

![image](https://github.com/user-attachments/assets/5b5ed931-d636-4859-ba00-8a494452b460)

**Comment by artistmatej** [comment]
I deleted numpy version 2.x and it started to work (I think numpy version 1.x should be installed).
