### ISSUE TITLE
why? my webcam is Cl-eye Driver.

### ISSUE THREAD

**Issue by qfb594** [cgtinker/BlendArMocap#21]
Python: Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\BlendArMocap-main\cgt_blender\interface\stream_detection_operator.py", line 40, in execute
    self.init_detector(detection_type)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\BlendArMocap-main\cgt_blender\interface\stream_detection_operator.py", line 60, in init_detector
    self.tracking_handler.stream = stream.Webcam(camera_index=camera_index)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\BlendArMocap-main\cgt_utils\stream.py", line 16, in __init__
    raise IOError("Cannot open webcam")
OSError: Cannot open webcam

location: <unknown location>:-1

**Comment by cgtinker** [comment]
I think opencv just didn't support your webcam. I've faced different issues by now regarding opencv and I think the only thing you could try is to test different opencv version manually. I've about to release an update next week (currently on the main branch), but this issue may still arise - checkout #131 if issues occur, consider to read the docs how to manually install opencv (and consider to test different versions)
