### ISSUE TITLE
Can't Start Detection

### ISSUE THREAD

**Issue by dh6i5ukds0** [cgtinker/BlendArMocap#3]
Hi! After I press the Start Detection button, there's an error command,

Error: Python: Traceback (most recent call last):
  File "C:\Users\*\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blender\interface\detection_operator.py", line 47, in execute
    self.init_detector(detection_type)
  File "C:\Users\*\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blender\interface\detection_operator.py", line 56, in init_detector
    from utils.open_cv import stream
  File "C:\Users\*\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\utils\open_cv\stream.py", line 1, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'

location: <unknown location>:-1

And before that, there's no Install Dependencies button on add-ons preferences.

**Comment by AbhijitL** [comment]
install the dependencies manually
 ```
 pip install opencv-python
 pip install mediapipe
 ```

**Comment by cgtinker** [comment]
The dependencies are required to run the add-on. Actually that shouldn't even possible to start a recording while dependencies are missing. So there is definitely something wrong.Did you start blender with elevated privileges?Which blender version and operating system are you using?Best regards, DenysOn 31 Jan 2022 05:34, dh6i5ukds0 ***@***.***> wrote:
Hi! After I press the Start Detection button, there's an error command,
Error: Python: Traceback (most recent call last):
File "C:\Users*\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blender\interface\detection_operator.py", line 47, in execute
self.init_detector(detection_type)
File "C:\Users*\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blender\interface\detection_operator.py", line 56, in init_detector
from utils.open_cv import stream
File "C:\Users*\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\utils\open_cv\stream.py", line 1, in 
import cv2
ModuleNotFoundError: No module named 'cv2'
location: :-1
And before that, there's no Install Dependencies button on add-ons preferences.

**Comment by cgtinker** [comment]
Was able to reproduce the bug - should be fixed now.
Make sure to run blender as admin - probably you have to restart blender during the setup process.

Best regards, Denys
