### ISSUE TITLE
regression: 1.4.0 can't access webcam

### ISSUE THREAD

**Issue by ebegu** [cgtinker/BlendArMocap#33]
Hi,
this is a great project, thank you for your hard work!

Version "BlendArMocap-beta-120.zip" (main branch) worked, but the dev branch downloaded on the 27th of March had the issue that the webcam window would not close anymore by pressing ESC and reopened immediately if closed by clicking on the X on the window header or using Alt-F4, so it was unusable. Also going back to the older version did not help, the issue persisted. Each version was removed before installing the new one.

Now with version 1.4.0 from main branch, the webcam window won't even open after clicking "start detection". 

Blender 3.1.0, platform: manjaro stable

Error message:
```
Python: Traceback (most recent call last):
  File "/root/.config/blender/3.1/scripts/addons/BlendArMocap-main/src/cgt_blender/interface/stream_detection_operator.py", line 39, in execute
    self.init_detector(detection_type)
  File "/root/.config/blender/3.1/scripts/addons/BlendArMocap-main/src/cgt_blender/interface/stream_detection_operator.py", line 59, in init_detector
    self.tracking_handler.stream = stream.Webcam(camera_index=camera_index)
  File "/root/.config/blender/3.1/scripts/addons/BlendArMocap-main/src/cgt_utils/stream.py", line 16, in __init__
    raise IOError("Cannot open webcam")
OSError: Cannot open webcam

location: <unknown location>:-1
```
After clicking it again:

```
Python: Exception ignored in: <function RealtimeDetector.__del__ at 0x7fc9d5033d90>
Traceback (most recent call last):
  File "/root/.config/blender/3.1/scripts/addons/BlendArMocap-main/src/cgt_detection/abstract_detector.py", line 102, in __del__
    self.listener.detach(self.observer)
AttributeError: 'NoneType' object has no attribute 'detach'
Traceback (most recent call last):
  File "/root/.config/blender/3.1/scripts/addons/BlendArMocap-main/src/cgt_blender/interface/stream_detection_operator.py", line 39, in execute
    self.init_detector(detection_type)
  File "/root/.config/blender/3.1/scripts/addons/BlendArMocap-main/src/cgt_blender/interface/stream_detection_operator.py", line 59, in init_detector
    self.tracking_handler.stream = stream.Webcam(camera_index=camera_index)
  File "/root/.config/blender/3.1/scripts/addons/BlendArMocap-main/src/cgt_utils/stream.py", line 16, in __init__
    raise IOError("Cannot open webcam")
OSError: Cannot open webcam

location: <unknown location>:-1
```

**Comment by cgtinker** [comment]
Hey there!

did you try pressing "Q" to finish the detection? Somehow it seems to be the most consistent, it may be required to press "Q" multiple times. Make sure you have the detection window selected when pressing "Q" / "ESC" / "LEFT-Mouse-Btn".

There is probably an issue with open-cv, I'm not certain. Do you use "0" as the webcam device slot? Is your webcam properly connected? Consider reinstalling open-cv - maybe it's corrupted. Didn't have an exception for this error, which leads to the error when you tried again...

**Comment by ebegu** [comment]
It is fixed, thank you!
Yes, Q is the only thing that closes the detection window.
