### ISSUE TITLE
Issue while installing dependencies (mac os 12.3.1, Blender 2.9.3)

### ISSUE THREAD

**Issue by inqtel** [cgtinker/BlendArMocap#50]
I get the following error message when trying to get the add on to install dependencies. I have mediapipe etc already installed. Per the instructions, I opened blender in admin mode through sudo command in terminal. Watching the progress there, it looked like finding/installing modules wasn't actually the issue, the error seems to come afterwards?

I'd love to get this add on working!!

Read prefs: /var/root/Library/Application Support/Blender/2.93/config/userpref.blend
BlendArMocap-release - Initializing...
PACKAGE: BlendArMocap-release
binary: /Applications/Blender.app/Contents/MacOS/Blender
blender version: (2, 93, 9) exe: /Applications/Blender.app/Contents/Resources/2.93/python/bin/python3.9
BlendArMocap-release - Dependencies installed: False
Registing BlendArMocap

Try to access dependencies
Dependency(module='mediapipe', package=None, name=None)
Exception in module register(): /var/root/Library/Application Support/Blender/2.93/scripts/addons/BlendArMocap-release/__init__.py
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 386, in enable
    mod.register()
  File "/var/root/Library/Application Support/Blender/2.93/scripts/addons/BlendArMocap-release/__init__.py", line 45, in register
    ui_registration.register()
  File "/var/root/Library/Application Support/Blender/2.93/scripts/addons/BlendArMocap-release/src/cgt_blender/interface/ui_registration.py", line 40, in register
    install_dependencies.import_module(module_name=dependency.module, global_name=dependency.name)
  File "/var/root/Library/Application Support/Blender/2.93/scripts/addons/BlendArMocap-release/src/cgt_blender/utils/install_dependencies.py", line 54, in import_module
    globals()[global_name] = importlib.import_module(global_name)
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/mediapipe/__init__.py", line 17, in <module>
    import mediapipe.python.solutions as solutions
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/mediapipe/python/solutions/__init__.py", line 17, in <module>
    import mediapipe.python.solutions.drawing_styles
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/mediapipe/python/solutions/drawing_styles.py", line 20, in <module>
    from mediapipe.python.solutions.drawing_utils import DrawingSpec
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/mediapipe/python/solutions/drawing_utils.py", line 25, in <module>
    from mediapipe.framework.formats import detection_pb2
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/mediapipe/framework/formats/detection_pb2.py", line 14, in <module>
    from mediapipe.framework.formats import location_data_pb2 as mediapipe_dot_framework_dot_formats_dot_location__data__pb2
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/mediapipe/framework/formats/location_data_pb2.py", line 14, in <module>
    from mediapipe.framework.formats.annotation import rasterization_pb2 as mediapipe_dot_framework_dot_formats_dot_annotation_dot_rasterization__pb2
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/mediapipe/framework/formats/annotation/rasterization_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/Applications/Blender.app/Contents/Resources/2.93/python/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

**Comment by haker1023** [comment]
Error message in last 5 lines are same with me when I first enable addon option block each time

**Comment by cgtinker** [comment]
Are you using the intel version of blender? (There's a silicone and a intel version downloaded at blender.org)

It seems like there is an issue with the mediapipe module. First make sure you are using the intel version. Secondly I'd try to delete the mediapipe module in the site packages and reinstall it. I'll try to reproduce this error soon.

**Comment by cgtinker** [comment]
Google recently updated their protobuffers and mediapipe didn't include the change in their dependencies. I've been working on a fix but only tested on windows so far - https://github.com/cgtinker/BlendArMocap/tree/development. 

Please try the development build and refer to #56
