### ISSUE TITLE
After install in addons, there's no dependencies pacakge button appears

### ISSUE THREAD

**Issue by haker1023** [cgtinker/BlendArMocap#52]
Here's error note

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\addon_utils.py", line 386, in enable
    mod.register()
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\BlendArMocap-main\__init__.py", line 45, in register
    ui_registration.register()
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\BlendArMocap-main\cgt_blender\interface\ui_registration.py", line 33, in register
    register_class(m_class)
ValueError: register_class(...): already registered as a subclass 'PREFERENCES_OT_install_dependencies_button'

Who knows what happend, The same result with my VPN on/off .

**Comment by haker1023** [comment]
I use blender 2.93 and pip upgraded, open-cv-python , mediapip installed , python is which blender's version

**Comment by cgtinker** [comment]
I've abstracted the name a little bit more, let me know if that fixes your issue.

https://github.com/cgtinker/BlendArMocap/tree/development

**Comment by cgtinker** [comment]
> I use blender 2.93 and pip upgraded, open-cv-python , mediapip installed , python is which blender's version



> I've abstracted the name a little bit more, let me know if that fixes your issue.
> 
> https://github.com/cgtinker/BlendArMocap/tree/development

did the update solve your issue?
