### ISSUE TITLE
windows 10/ it not work

### ISSUE THREAD

**Issue by soooon-wang** [cgtinker/BlendArMocap#54]
Python: Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlendArMocap-release\src\cgt_blender\interface\ui_preferences.py", line 31, in execute
    global_name=dependency.name)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlendArMocap-release\src\cgt_blender\utils\install_dependencies.py", line 94, in install_and_import_module
    import_module(module_name, global_name)
  File "C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\BlendArMocap-release\src\cgt_blender\utils\install_dependencies.py", line 54, in import_module
    globals()[global_name] = importlib.import_module(global_name)
  File "D:\Program Files\blender\blender-2.91.2-windows64\2.91\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Program Files\blender\blender-2.91.2-windows64\2.91\python\lib\site-packages\mediapipe\__init__.py", line 17, in <module>
    import mediapipe.python.solutions as solutions
  File "D:\Program Files\blender\blender-2.91.2-windows64\2.91\python\lib\site-packages\mediapipe\python\solutions\__init__.py", line 17, in <module>
    import mediapipe.python.solutions.drawing_styles
  File "D:\Program Files\blender\blender-2.91.2-windows64\2.91\python\lib\site-packages\mediapipe\python\solutions\drawing_styles.py", line 20, in <module>
    from mediapipe.python.solutions.drawing_utils import DrawingSpec
  File "D:\Program Files\blender\blender-2.91.2-windows64\2.91\python\lib\site-packages\mediapipe\python\solutions\drawing_utils.py", line 25, in <module>
    from mediapipe.framework.formats import detection_pb2
  File "D:\Program Files\blender\blender-2.91.2-windows64\2.91\python\lib\site-packages\mediapipe\framework\formats\detection_pb2.py", line 16, in <module>
    from mediapipe.framework.formats import location_data_pb2 as mediapipe_dot_framework_dot_formats_dot_location__data__pb2
  File "D:\Program Files\blender\blender-2.91.2-windows64\2.91\python\lib\site-packages\mediapipe\framework\formats\location_data_pb2.py", line 16, in <module>
    from mediapipe.framework.formats.annotation import rasterization_pb2 as mediapipe_dot_framework_dot_formats_dot_annotation_dot_rasterization__pb2
  File "D:\Program Files\blender\blender-2.91.2-windows64\2.91\python\lib\site-packages\mediapipe\framework\formats\annotation\rasterization_pb2.py", line 42, in <module>
    options=None),
  File "D:\Program Files\blender\blender-2.91.2-windows64\2.91\python\lib\site-packages\google\protobuf\descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

location: <unknown location>:-1

run as admins 
  VPN on/off, blender 2.90 2.91 2.93 3.0 3.1 ,but not work!

**Comment by AvasavA** [comment]
same here i have been trying to downgrade the protobuf package to 3.20
or use this command PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python but no luck most info for it is for linux users python there is not the same as windows

**Comment by cgtinker** [comment]
I'll try to reproduce this soon, there seems to be an issue with the new protobuf version in mediapipe.

Could u try to change the protobuf version using the cmd? I don't know if blender relies on the protobuf version, so preferably download a fresh blender version before trying it.

1. find the path to your blender python executable (usually located in the _blender folder/resources/version/python/bin_)
2. _path/to/python_executeable_ -ensurepip
3. _path/to/python_executeable_ pip install protobuf==3.2.0

**Comment by AvasavA** [comment]
thanks, sir i think it used to work but when i updated to blender 3.2 and had to install it again that happened plus they just released the new version of protobuf but i am not that sure because i don't really use python
but thank you a lot for your hard work i live in a 3-word country and i never even dreamt of having something like that awesome work

**Comment by AvasavA** [comment]
> I'll try to reproduce this soon, there seems to be an issue with the new protobuf version in mediapipe.
> 
> Could u try to change the protobuf version using the cmd? I don't know if blender relies on the protobuf version, so preferably download a fresh blender version before trying it.
> 
> 1. find the path to your blender python executable (usually located in the _blender folder/resources/version/python/bin_)
> 2. _path/to/python_executeable_ ensurepip
> 3. _path/to/python_executeable_ pip install protobuf==3.2.0

i am not sure how to apllay that do you want me to write it like this 
C:\Program Files\Blender Foundation\Blender 3.1\3.1\python\bin\python.exe ensurepip

**Comment by cgtinker** [comment]
I've been working on a fix, please refer  #56
