### ISSUE TITLE
Install Dependences lot bug Blender 3.3.0 Alpha

### ISSUE THREAD

**Issue by mac4kent** [cgtinker/BlendArMocap#55]
Preferences on Add-on have lot bug install dependences button
Blender 3.3.0 Alpha

<img width="654" alt="image" src="https://user-images.githubusercontent.com/4253305/171456476-d44a5f7f-efa1-472d-8d89-17c28d3b3269.png">

<img width="1365" alt="image" src="https://user-images.githubusercontent.com/4253305/171456384-88a997d0-7f42-4199-9232-49ed517e33c0.png">

**Comment by mac4kent** [comment]
Blender 2.9x, 3.0.x, 3.1.x still not work because of 
![image](https://user-images.githubusercontent.com/4253305/171696590-ae966f07-8740-4cce-8082-3d17a7dc02d5.png)


I do use MacOS 12

**Comment by mac4kent** [comment]
Why you put close too fast!!!????

**Comment by mac4kent** [comment]
Sigh!
I do use Intel iMac 2017 i5.
What is silicone?

**Comment by cgtinker** [comment]
Mac's with the new M1 processor often refer to 'blenders silicone' version. Though U use it's because of the operating system.

When does the error occur? Upon start, after pressing the install dependencies button or  when pressing the start detection button?

Did you start blender as admin using the console? It would be awesome if you could copy and paste here the full error message from the console.

**Comment by mac4kent** [comment]
M1 I not have money to get one. I have limit SSDI income.
I did pressing the install dependencies button for a while cause appear error (picture above).
I got download from Blender 2.9x, 3.0, 3.1 also 3.3.0 Alpha from blender.org
I don't know how to make ADMIN some where?

**Comment by cgtinker** [comment]
Start Blender as admin by using the terminal:

Navigate to Blender: cd /Applications/Blender/Contents/MacOS

Run Blender as admin: sudo ./Blender

**Comment by mac4kent** [comment]
sudo ./blend auto open itself.
Now what next?

**Comment by mac4kent** [comment]
June 2, 2022
Blender 2.90.1 just now download at 2:00 PM Pacific Time

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Youtube:https://youtu.be/RpvgTxikt1w
(Right click "Open Package Contents") already.

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

Terminal.app
kentdavis@Kents-iMac MacOS % cd /Applications/Blender\ 2.90.1.app/Contents/MacOS 
kentdavis@Kents-iMac MacOS % sudo ./blender
Password:
found bundled python: /Applications/Blender 2.90.1.app/Contents/Resources/2.90/python
addon_utils.disable: BlendArMocap-release not disabled
Modules Installed (BlendArMocap-release) from '/Users/kentdavis/Documents/Blender 2.8/1 Install/Add ons/Blend Ar Mocap/BlendArMocap-release-v141.zip' into '/var/root/Library/Application Support/Blender/2.90/scripts/addons'
BlendArMocap-release - Initializing...
PACKAGE: BlendArMocap-release
binary: /Applications/Blender 2.90.1.app/Contents/MacOS/blender
blender version: (2, 90, 1) exe: /Applications/Blender 2.90.1.app/Contents/Resources/2.90/python/bin/python3.7m
BlendArMocap-release - Dependencies installed: False
Registing BlendArMocap

Try to access dependencies
Dependency(module='mediapipe', package=None, name=None)
REGISTRATION FAILED: REQUIRED MODULE NOT FOUND
accessing pip installer
/Applications/Blender 2.90.1.app/Contents/Resources/2.90/python/bin/python3.7m -m pip --version
pip 19.2.3 from /Applications/Blender 2.90.1.app/Contents/Resources/2.90/python/lib/python3.7/site-packages/pip (python 3.7)
['/Applications/Blender 2.90.1.app/Contents/Resources/2.90/python/bin/python3.7m', '-m', 'pip', 'install', '--upgrade', 'pip']
WARNING: The directory '/Users/kentdavis/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/Users/kentdavis/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pip
  Downloading https://files.pythonhosted.org/packages/96/2f/caec18213f6a67852f6997fb0673ae08d2e93d1b81573edb93ba4ef06970/pip-22.1.2-py3-none-any.whl (2.1MB)
     |████████████████████████████████| 2.2MB 4.1MB/s 
Installing collected packages: pip
  Found existing installation: pip 19.2.3
    Uninstalling pip-19.2.3:
      Successfully uninstalled pip-19.2.3
Successfully installed pip-22.1.2
Try to install: mediapipe
/Applications/Blender 2.90.1.app/Contents/Resources/2.90/python/bin/python3.7m -m pip install mediapipe
WARNING: The directory '/Users/kentdavis/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Collecting mediapipe
  Downloading mediapipe-0.8.10-cp37-cp37m-macosx_10_15_x86_64.whl (33.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.6/33.6 MB 27.5 MB/s eta 0:00:00
Collecting attrs>=19.1.0
  Downloading attrs-21.4.0-py2.py3-none-any.whl (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 145.6 MB/s eta 0:00:00
Collecting opencv-contrib-python
  Downloading opencv_contrib_python-4.5.5.64-cp36-abi3-macosx_10_15_x86_64.whl (55.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.9/55.9 MB 28.1 MB/s eta 0:00:00
Collecting absl-py
  Downloading absl_py-1.1.0-py3-none-any.whl (123 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 123.7/123.7 kB 158.2 MB/s eta 0:00:00
Collecting matplotlib
  Downloading matplotlib-3.5.2-cp37-cp37m-macosx_10_9_x86_64.whl (7.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.3/7.3 MB 29.3 MB/s eta 0:00:00
Collecting protobuf>=3.11.4
  Downloading protobuf-4.21.1-cp37-abi3-macosx_10_9_universal2.whl (483 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 483.1/483.1 kB 41.7 MB/s eta 0:00:00
Requirement already satisfied: numpy in /Applications/Blender 2.90.1.app/Contents/Resources/2.90/python/lib/python3.7/site-packages (from mediapipe) (1.17.5)
Collecting packaging>=20.0
  Downloading packaging-21.3-py3-none-any.whl (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.8/40.8 kB 118.0 MB/s eta 0:00:00
Collecting python-dateutil>=2.7
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 kB 58.8 MB/s eta 0:00:00
Collecting cycler>=0.10
  Downloading cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting pillow>=6.2.0
  Downloading Pillow-9.1.1-cp37-cp37m-macosx_10_10_x86_64.whl (3.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 30.1 MB/s eta 0:00:00
Collecting fonttools>=4.22.0
  Downloading fonttools-4.33.3-py3-none-any.whl (930 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 930.9/930.9 kB 33.3 MB/s eta 0:00:00
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.4.2-cp37-cp37m-macosx_10_9_x86_64.whl (65 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 65.1/65.1 kB 140.4 MB/s eta 0:00:00
Collecting pyparsing>=2.2.1
  Downloading pyparsing-3.0.9-py3-none-any.whl (98 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.3/98.3 kB 163.0 MB/s eta 0:00:00
Collecting typing-extensions
  Downloading typing_extensions-4.2.0-py3-none-any.whl (24 kB)
Collecting six>=1.5
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: typing-extensions, six, pyparsing, protobuf, pillow, opencv-contrib-python, fonttools, cycler, attrs, absl-py, python-dateutil, packaging, kiwisolver, matplotlib, mediapipe
Successfully installed absl-py-1.1.0 attrs-21.4.0 cycler-0.11.0 fonttools-4.33.3 kiwisolver-1.4.2 matplotlib-3.5.2 mediapipe-0.8.10 opencv-contrib-python-4.5.5.64 packaging-21.3 pillow-9.1.1 protobuf-4.21.1 pyparsing-3.0.9 python-dateutil-2.8.2 six-1.16.0 typing-extensions-4.2.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Installation process finished
Traceback (most recent call last):
  File "/var/root/Library/Application Support/Blender/2.90/scripts/addons/BlendArMocap-release/src/cgt_blender/interface/ui_preferences.py", line 31, in execute
    global_name=dependency.name)
  File "/var/root/Library/Application Support/Blender/2.90/scripts/addons/BlendArMocap-release/src/cgt_blender/utils/install_dependencies.py", line 94, in install_and_import_module
    import_module(module_name, global_name)
  File "/var/root/Library/Application Support/Blender/2.90/scripts/addons/BlendArMocap-release/src/cgt_blender/utils/install_dependencies.py", line 54, in import_module
    globals()[global_name] = importlib.import_module(global_name)
  File "/Applications/Blender 2.90.1.app/Contents/Resources/2.90/python/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Applications/Blender 2.90.1.app/Contents/Resources/2.90/python/lib/python3.7/site-packages/mediapipe/__init__.py", line 17, in <module>
    import mediapipe.python.solutions as solutions
  File "/Applications/Blender 2.90.1.app/Contents/Resources/2.90/python/lib/python3.7/site-packages/mediapipe/python/solutions/__init__.py", line 17, in <module>
    import mediapipe.python.solutions.drawing_styles
  File "/Applications/Blender 2.90.1.app/Contents/Resources/2.90/python/lib/python3.7/site-packages/mediapipe/python/solutions/drawing_styles.py", line 20, in <module>
    from mediapipe.python.solutions.drawing_utils import DrawingSpec
  File "/Applications/Blender 2.90.1.app/Contents/Resources/2.90/python/lib/python3.7/site-packages/mediapipe/python/solutions/drawing_utils.py", line 25, in <module>
    from mediapipe.framework.formats import detection_pb2
  File "/Applications/Blender 2.90.1.app/Contents/Resources/2.90/python/lib/python3.7/site-packages/mediapipe/framework/formats/detection_pb2.py", line 14, in <module>
    from mediapipe.framework.formats import location_data_pb2 as mediapipe_dot_framework_dot_formats_dot_location__data__pb2
  File "/Applications/Blender 2.90.1.app/Contents/Resources/2.90/python/lib/python3.7/site-packages/mediapipe/framework/formats/location_data_pb2.py", line 14, in <module>
    from mediapipe.framework.formats.annotation import rasterization_pb2 as mediapipe_dot_framework_dot_formats_dot_annotation_dot_rasterization__pb2
  File "/Applications/Blender 2.90.1.app/Contents/Resources/2.90/python/lib/python3.7/site-packages/mediapipe/framework/formats/annotation/rasterization_pb2.py", line 42, in <module>
    serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  File "/Applications/Blender 2.90.1.app/Contents/Resources/2.90/python/lib/python3.7/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

location: <unknown location>:-1

location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "/var/root/Library/Application Support/Blender/2.90/scripts/addons/BlendArMocap-release/src/cgt_blender/interface/ui_preferences.py", line 31, in execute
    global_name=dependency.name)
  File "/var/root/Library/Application Support/Blender/2.90/scripts/addons/BlendArMocap-release/src/cgt_blender/utils/install_dependencies.py", line 94, in install_and_import_module
    import_module(module_name, global_name)
  File "/var/root/Library/Application Support/Blender/2.90/scripts/addons/BlendArMocap-release/src/cgt_blender/utils/install_dependencies.py", line 54, in import_module
    globals()[global_name] = importlib.import_module(global_name)
  File "/Applications/Blender 2.90.1.app/Contents/Resources/2.90/python/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Applications/Blender 2.90.1.app/Contents/Resources/2.90/python/lib/python3.7/site-packages/mediapipe/__init__.py", line 17, in <module>
    import mediapipe.python.solutions as solutions
  File "/Applications/Blender 2.90.1.app/Contents/Resources/2.90/python/lib/python3.7/site-packages/mediapipe/python/solutions/__init__.py", line 17, in <module>
    import mediapipe.python.solutions.drawing_styles
  File "/Applications/Blender 2.90.1.app/Contents/Resources/2.90/python/lib/python3.7/site-packages/mediapipe/python/solutions/drawing_styles.py", line 20, in <module>
    from mediapipe.python.solutions.drawing_utils import DrawingSpec
  File "/Applications/Blender 2.90.1.app/Contents/Resources/2.90/python/lib/python3.7/site-packages/mediapipe/python/solutions/drawing_utils.py", line 25, in <module>
    from mediapipe.framework.formats import detection_pb2
  File "/Applications/Blender 2.90.1.app/Contents/Resources/2.90/python/lib/python3.7/site-packages/mediapipe/framework/formats/detection_pb2.py", line 14, in <module>
    from mediapipe.framework.formats import location_data_pb2 as mediapipe_dot_framework_dot_formats_dot_location__data__pb2
  File "/Applications/Blender 2.90.1.app/Contents/Resources/2.90/python/lib/python3.7/site-packages/mediapipe/framework/formats/location_data_pb2.py", line 14, in <module>
    from mediapipe.framework.formats.annotation import rasterization_pb2 as mediapipe_dot_framework_dot_formats_dot_annotation_dot_rasterization__pb2
  File "/Applications/Blender 2.90.1.app/Contents/Resources/2.90/python/lib/python3.7/site-packages/mediapipe/framework/formats/annotation/rasterization_pb2.py", line 42, in <module>
    serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  File "/Applications/Blender 2.90.1.app/Contents/Resources/2.90/python/lib/python3.7/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

location: <unknown location>:-1


Saved session recovery to '/tmp/quit.blend'
Writing userprefs: '/var/root/Library/Application Support/Blender/2.90/config/userpref.blend' ok

Blender quit
kentdavis@Kents-iMac MacOS %

**Comment by mac4kent** [comment]
<img width="3200" alt="image" src="https://user-images.githubusercontent.com/4253305/171747089-c56be6dc-1a8c-4685-9314-0d0a1560dacb.png">


<img width="679" alt="image" src="https://user-images.githubusercontent.com/4253305/171747169-32a884c4-c5ab-4387-a7f0-f82327f66b21.png">

<img width="3200" alt="image" src="https://user-images.githubusercontent.com/4253305/171747590-a3205627-ab60-4ed8-b2d7-0b42634c088b.png">

**Comment by mac4kent** [comment]
Better to use this Library on Terminal: /Users/kentdavis/Library/Application\ Support/Blender/2.90/scripts/addons 
<img width="3200" alt="image" src="https://user-images.githubusercontent.com/4253305/171749070-b6d46efe-61d0-405f-811b-1b316ae09057.png">

**Comment by cgtinker** [comment]
Thanks a lot for the details. I'm working on an update and fix atm which I'm still testing.
Google updated their protobuf version this week which lead to a mismatch with the protobuf version of mediapipe.

Please download my development version - it should resolve the issue.
https://github.com/cgtinker/BlendArMocap/tree/development
(CODE > Download Zip)

If you have further issues with the protobuf version please refer to issue #56

**Comment by mac4kent** [comment]
I has been fight and fight delete then install through ADMIN Terminal.app until finally 
<img width="3200" alt="image" src="https://user-images.githubusercontent.com/4253305/171751883-8ceb2126-e7b7-4600-8d27-d03849213a76.png">

**Comment by mac4kent** [comment]
Blender 3.3.0 Alpha you can see 
<img width="3200" alt="image" src="https://user-images.githubusercontent.com/4253305/171752603-b9cd712c-2901-4991-925a-03f3677a7ec3.png">

through Terminal.app

**Comment by mac4kent** [comment]
I forget to show you preferences full . 
<img width="3200" alt="image" src="https://user-images.githubusercontent.com/4253305/171752787-a04ce3e7-d468-4570-81ae-aa8f07ccb17f.png">

**Comment by mac4kent** [comment]
Just open app without terminal.
<img width="3200" alt="image" src="https://user-images.githubusercontent.com/4253305/171753107-7457273e-ec54-4f57-a7bf-ebabcbea307b.png">

Blender 3.3.0 Alpha you see.

**Comment by mac4kent** [comment]
Blender within Terminal any version it work as well Blender 2.9, 3.0, 3.1, 3.2, 3.3.0 Alpha it work as well.
without Terminal.app just open Blender for sure CRASH GUIDE all version.

**Comment by cgtinker** [comment]
Not sure if it requires the sudo (password) once you have given your terminal camera permissions. ./blender should be enough.

On MacOS that's expected. That's due to permissions - blender would require camera permissions to run stream detection on Mac which is easy to overcome with the terminal.
Please read the 'ReadMe' either on GitHub or in zip. 


Glad it runs now!

**Comment by mac4kent** [comment]
Thank you for explain me no problem
Yes it running now.
