### ISSUE TITLE
Dependency TypeError: Descriptors cannot not be created directly. PROTOCOL_BUFFERS_PYTHON

### ISSUE THREAD

**Issue by griseldarosario** [cgtinker/BlendArMocap#56]
REGISTERING BLENDARMOCAP
TRY ACCESS INSTALLED DEPENDENCIES
Dependency(module='mediapipe', package=None, name=None)
Exception in module register(): C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlendArMocap-main\__init__.py
Traceback (most recent call last):
  File "C:\Users\User\Downloads\blender-2.90.1-windows64\2.90\scripts\modules\addon_utils.py", line 382, in enable
    mod.register()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlendArMocap-main\__init__.py", line 45, in register
    ui_registration.register()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlendArMocap-main\cgt_blender\interface\ui_registration.py", line 39, in register
    install_dependencies.import_module(module_name=dependency.module, global_name=dependency.name)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\BlendArMocap-main\cgt_blender\utils\install_dependencies.py", line 34, in import_module
    globals()[global_name] = importlib.import_module(global_name)
  File "C:\Users\User\Downloads\blender-2.90.1-windows64\2.90\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\User\Downloads\blender-2.90.1-windows64\2.90\python\lib\site-packages\mediapipe\__init__.py", line 17, in <module>
    import mediapipe.python.solutions as solutions
  File "C:\Users\User\Downloads\blender-2.90.1-windows64\2.90\python\lib\site-packages\mediapipe\python\solutions\__init__.py", line 17, in <module>
    import mediapipe.python.solutions.drawing_styles
  File "C:\Users\User\Downloads\blender-2.90.1-windows64\2.90\python\lib\site-packages\mediapipe\python\solutions\drawing_styles.py", line 20, in <module>
    from mediapipe.python.solutions.drawing_utils import DrawingSpec
  File "C:\Users\User\Downloads\blender-2.90.1-windows64\2.90\python\lib\site-packages\mediapipe\python\solutions\drawing_utils.py", line 25, in <module>
    from mediapipe.framework.formats import detection_pb2
  File "C:\Users\User\Downloads\blender-2.90.1-windows64\2.90\python\lib\site-packages\mediapipe\framework\formats\detection_pb2.py", line 16, in <module>
    from mediapipe.framework.formats import location_data_pb2 as mediapipe_dot_framework_dot_formats_dot_location__data__pb2
  File "C:\Users\User\Downloads\blender-2.90.1-windows64\2.90\python\lib\site-packages\mediapipe\framework\formats\location_data_pb2.py", line 16, in <module>
    from mediapipe.framework.formats.annotation import rasterization_pb2 as mediapipe_dot_framework_dot_formats_dot_annotation_dot_rasterization__pb2
  File "C:\Users\User\Downloads\blender-2.90.1-windows64\2.90\python\lib\site-packages\mediapipe\framework\formats\annotation\rasterization_pb2.py", line 42, in <module>
    options=None),
  File "C:\Users\User\Downloads\blender-2.90.1-windows64\2.90\python\lib\site-packages\google\protobuf\descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates

**Comment by griseldarosario** [comment]
I'm using Blender 2.90.1 and I cannot use BlendArMocap

**Comment by soooon-wang** [comment]
[cgtinker](https://github.com/cgtinker) commented [2 days ago](https://github.com/cgtinker/BlendArMocap/issues/54#issuecomment-1141954720) • 
I'll try to reproduce this soon, there seems to be an issue with the new protobuf version in mediapipe.

Could u try to change the protobuf version using the cmd? I don't know if blender relies on the protobuf version, so preferably download a fresh blender version before trying it.

find the path to your blender python executable (usually located in the blender folder/resources/version/python/bin)
path/to/python_executeable ensurepip
path/to/python_executeable pip install protobuf==3.2.0


I don't konw how to change the protobuf version by use zhe cmd!
Would you know?

**Comment by cgtinker** [comment]
I was able to reproduce the bug. Please download and try the development version.

If you install the BlendArMocap-development version on windows in the same Blender.exe you've previously installed BlendArMocap it will throw some bugs on (esp) windows after installing -  this is due to permission and how Blender handles site-packages. In this case, just restart Blender and everything should work as expected. The same is true for uninstalling the packages in the add-on's preferences. The remains of the site-packages are getting purged upon restart.

https://github.com/cgtinker/BlendArMocap/tree/development

**Comment by griseldarosario** [comment]
Thanks a lot, it works! Great! (:

**Comment by cgtinker** [comment]
V1.5.0 which implements the fix is now up on the main branch.
