### ISSUE TITLE
Movie detection - OSError: Cannot open webcam

### ISSUE THREAD

**Issue by ebegu** [cgtinker/BlendArMocap#62]
Hi,

Movie detection does not work if the blend file has been saved before with detection type Stream or Movie without providing a filepath.
- open blender, open n panel, select BlendArMocap, switch type to Movie, select mov file, start detection works (also after saving/reopening file).
If you save without a filepath, you will get the error below, even if you keep the file open after saving and fill in the path, it will still result in the error.
- open blender, open n panel, select BlendArMocap, save file, reopen file, switch type to Movie, select mov file, start detection does not work and this error appears: _OSError: Cannot open webcam_ .
It does not happen in a new file. Using armocap 1.5.1.

```
Python: DEL STREAM
Exception ignored in: <function RealtimeDetector.__del__ at 0x7f0ea0e481f0>
Traceback (most recent call last):
  File "/home/ebegu/.config/blender/3.1/scripts/addons/BlendArMocap-release/src/cgt_detection/detector_interface.py", line 121, in __del__
    self.listener.detach(self.observer)
AttributeError: 'NoneType' object has no attribute 'detach'
Traceback (most recent call last):
  File "/home/ebegu/.config/blender/3.1/scripts/addons/BlendArMocap-release/src/cgt_blender/interface/ui_operators.py", line 79, in execute
    self.detection_handler.init_detector(mov_path, "sd", 0, frame_start, 1, 1)
  File "/home/ebegu/.config/blender/3.1/scripts/addons/BlendArMocap-release/src/main.py", line 116, in init_detector
    self.detector.stream = stream.Webcam(
  File "/home/ebegu/.config/blender/3.1/scripts/addons/BlendArMocap-release/src/cgt_utils/stream.py", line 48, in __init__
    raise IOError("Cannot open webcam")
OSError: Cannot open webcam

location: <unknown location>:-1
```

**Comment by cgtinker** [comment]
Interesting, will try to reproduce this and plan to fix it in the next update.

**Comment by cgtinker** [comment]
had another high priority issue so I've already made an update. 
should be fixed in v152. path to files which aren't valid movie files may still cause this error. not sure yet which formats I can / cannot except so this has to be tested in the future
