### ISSUE TITLE
Addon - Installation

### ISSUE THREAD

**Issue by brnocg** [cgtinker/BlendArMocap#69]
Hey,

I'm trying to install the addon but isn't working. I'm following these steps:

- Run Administrator Mode
- Install Addon 
- Tested 2.93 LTS until 3.2

Receiving this error:

```
BlendArMocap-main - Initializing...
BlendArMocap-main - Dependencies installed: True
BlendArMocap-main - Attempt to reload...
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\brunn\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\BlendArMocap-main\__init__.py", line 40, in <module>
    reload_modules()
  File "C:\Users\brunn\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\BlendArMocap-main\__init__.py", line 36, in reload_modules
    cgt_imports.manage_imports()
  File "C:\Users\brunn\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\BlendArMocap-main\src\cgt_imports.py", line 100, in manage_imports
    import_module(module)
  File "C:\Users\brunn\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\BlendArMocap-main\src\cgt_imports.py", line 52, in import_module
    importlib.import_module(f"{PACKAGE_NAME}{module}")
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\brunn\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\BlendArMocap-main\src\cgt_detection\detector_interface.py", line 20, in <module>
    from mediapipe import solutions
ModuleNotFoundError: No module named 'mediapipe'

```

**Comment by brnocg** [comment]
Update:

Using 2.93 LTS and 1.4.1 version - Received this error trying to install dependencies

```
location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\brunn\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\BlendArMocap-release\src\cgt_blender\interface\ui_preferences.py", line 29, in execute
    install_dependencies.install_and_import_module(module_name=dependency.module,
  File "C:\Users\brunn\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\BlendArMocap-release\src\cgt_blender\utils\install_dependencies.py", line 94, in install_and_import_module
    import_module(module_name, global_name)
  File "C:\Users\brunn\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\BlendArMocap-release\src\cgt_blender\utils\install_dependencies.py", line 54, in import_module
    globals()[global_name] = importlib.import_module(global_name)
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\mediapipe\__init__.py", line 17, in <module>
    import mediapipe.python.solutions as solutions
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\mediapipe\python\solutions\__init__.py", line 17, in <module>
    import mediapipe.python.solutions.drawing_styles
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\mediapipe\python\solutions\drawing_styles.py", line 20, in <module>
    from mediapipe.python.solutions.drawing_utils import DrawingSpec
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\mediapipe\python\solutions\drawing_utils.py", line 25, in <module>
    from mediapipe.framework.formats import detection_pb2
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\mediapipe\framework\formats\detection_pb2.py", line 16, in <module>
    from mediapipe.framework.formats import location_data_pb2 as mediapipe_dot_framework_dot_formats_dot_location__data__pb2
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\mediapipe\framework\formats\location_data_pb2.py", line 16, in <module>
    from mediapipe.framework.formats.annotation import rasterization_pb2 as mediapipe_dot_framework_dot_formats_dot_annotation_dot_rasterization__pb2
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\mediapipe\framework\formats\annotation\rasterization_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "C:\Program Files\Blender Foundation\Blender 2.93\2.93\python\lib\site-packages\google\protobuf\descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```

**Comment by brnocg** [comment]
Fixed using the code development :)

Thanks for this amazing addon :)
