### ISSUE TITLE
Error while installing mediapipe BlendArMocap in Linux Blender 

### ISSUE THREAD

**Issue by AuraNETinfo** [cgtinker/BlendArMocap#83]
I can't install the dependencies and use Blneder on my Linux Ubuntu. Even logging in with admin privileges. The errors shown in the image below appear.

BlendArMocap-main - Initializing...
BlendArMocap-main - add-on path: /root/.config/blender/3.2/scripts/addons/BlendArMocap-main
BlendArMocap-main - blender bin: /snap/blender/2578/blender, blender version: (3, 2, 1)
BlendArMocap-main - python exe: /snap/blender/2578/3.2/python/bin/python3.10
Traceback (most recent call last):
  File "/snap/blender/2578/3.2/scripts/modules/addon_utils.py", line 335, in enable
    mod = __import__(module_name)
  File "/root/.config/blender/3.2/scripts/addons/BlendArMocap-main/__init__.py", line 40, in <module>
    reload_modules()
  File "/root/.config/blender/3.2/scripts/addons/BlendArMocap-main/__init__.py", line 36, in reload_modules
    cgt_imports.manage_imports()
  File "/root/.config/blender/3.2/scripts/addons/BlendArMocap-main/src/cgt_imports.py", line 84, in manage_imports
    import_module(module)
  File "/root/.config/blender/3.2/scripts/addons/BlendArMocap-main/src/cgt_imports.py", line 51, in import_module
    importlib.import_module(f"{PACKAGE_NAME}{module}")
  File "/snap/blender/2578/3.2/python/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/root/.config/blender/3.2/scripts/addons/BlendArMocap-main/src/cgt_blender/interface/ui_registration.py", line 22, in <module>
    from . import ui_properties, ui_panels, pref_operators, pref_panels, ui_operators
  File "/root/.config/blender/3.2/scripts/addons/BlendArMocap-main/src/cgt_blender/interface/ui_panels.py", line 21, in <module>
    from . import pref_operators
  File "/root/.config/blender/3.2/scripts/addons/BlendArMocap-main/src/cgt_blender/interface/pref_operators.py", line 24, in <module>
    from ..utils import dependencies
  File "/root/.config/blender/3.2/scripts/addons/BlendArMocap-main/src/cgt_blender/utils/dependencies.py", line 410, in <module>
    for is_installed, corrupted_dependency in analyze_dependencies(required_dependencies):
  File "/root/.config/blender/3.2/scripts/addons/BlendArMocap-main/src/cgt_blender/utils/dependencies.py", line 356, in analyze_dependencies
    if not is_package_installed(_dependency):
  File "/root/.config/blender/3.2/scripts/addons/BlendArMocap-main/src/cgt_blender/utils/dependencies.py", line 116, in is_package_installed
    package = importlib.util.find_spec(_dependency.name)
AttributeError: module 'importlib' has no attribute 'util'
addon_utils.disable: BlendArMocap-main not disabled
BlendArMocap-main - Initializing...
BlendArMocap-main - blender bin: /snap/blender/2578/blender, blender version: (3, 2, 1)
BlendArMocap-main - python exe: /snap/blender/2578/3.2/python/bin/python3.10
Registing BlendArMocap

Try to access dependencies
REGISTRATION FAILED: REQUIRED MODULE NOT FOUND
Attempting to install pip.
Defaulting to user installation because normal site-packages is not writeable
Looking in links: /tmp/tmpx7d4bt7i
Requirement already satisfied: setuptools in /root/.local/lib/python3.10/site-packages (58.1.0)
Requirement already satisfied: pip in /root/.local/lib/python3.10/site-packages (21.2.4)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Attempting to install: opencv-contrib-python>=4.5.5.64
['/snap/blender/2578/3.2/python/bin/python3.10', '-m', 'pip', 'install', '--no-cache-dir', 'opencv-contrib-python>=4.5.5.64']
/snap/blender/2578/3.2/python/bin/python3.10: No module named pip
Cannot install opencv-contrib-python>=4.5.5.64.
Attempting to install: protobuf>=3.11.4,<=3.20.0
['/snap/blender/2578/3.2/python/bin/python3.10', '-m', 'pip', 'install', '--no-cache-dir', 'protobuf>=3.11.4,<=3.20.0']
/snap/blender/2578/3.2/python/bin/python3.10: No module named pip
Cannot install protobuf>=3.11.4,<=3.20.0.
Attempting to install: mediapipe>=0.8.10
['/snap/blender/2578/3.2/python/bin/python3.10', '-m', 'pip', 'install', '--no-cache-dir', 'mediapipe>=0.8.10']
/snap/blender/2578/3.2/python/bin/python3.10: No module named pip
Cannot install mediapipe>=0.8.10.
BlendArMocap-main - Initializing...
BlendArMocap-main - blender bin: /snap/blender/2578/blender, blender version: (3, 2, 1)
BlendArMocap-main - python exe: /snap/blender/2578/3.2/python/bin/python3.10
BlendArMocap-main - Dependencies installed: False
[https://www.ilista.com.br/tmp/temp.jpeg](url)

**Comment by Iansamit** [comment]
I'm guessing you have a snap installation, which doesn't include Pip. Take a look at issue #59: https://github.com/cgtinker/BlendArMocap/issues/59
In the last two posts I detailed my solution. I'm afraid it involved replacing the snap version of Blender with the stand-alone version downloaded from the Blender website. This is the only way I could get past the snap permission restrictions. 
Anyway, I hope this helps.

**Comment by AuraNETinfo** [comment]
After a lot of trying I managed to install it, but now there is another problem when transferring the animation to the rig this error appears:

Python: Traceback (most recent call last):
  File "C:\Users\aucel\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlendArMocap-development\src\cgt_blender\interface\ui_operators.py", line 33, in execute
    input_manager.transfer_animation()
  File "C:\Users\aucel\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlendArMocap-development\src\cgt_blender\input_manager.py", line 45, in transfer_animation
    col_mapping[col](armature, driver_objects)
KeyError: 'Drivers'

**Comment by cgtinker** [comment]
> There is no error, in fact it was because I didn't select the correct driver, it would be good in the next update to verify that the driver was correctly selected before clicking on transfer animation.
> 
> cgtincker is to be congratulated on making this tool available for free, it will certainly be rewarded.

thanks, considering to make a pop up in the future 👍 
currently I'm working on a standalone exe to get rid of dependency issues, hopefully it allows to bypass the issues in the future
