### ISSUE TITLE
OSError: Cannot open webcam

### ISSUE THREAD

**Issue by xiaowen214** [cgtinker/BlendArMocap#85]
Hello, thanks for your work, the app installed but can't open the cam

Python: DEL STREAM
Exception ignored in: <function RealtimeDetector.__del__ at 0x000001DC101CDC60>
Traceback (most recent call last):
  File "C:\Users\********\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlendArMocap-main\src\cgt_detection\detector_interface.py", line 121, in __del__
    self.listener.detach(self.observer)
AttributeError: 'NoneType' object has no attribute 'detach'
[ERROR] mpfb.init ..............................: Unhandled crash 
  File "C:\Users\********\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlendArMocap-main\src\cgt_blender\interface\ui_operators.py", line 120, in execute
    self.detection_handler.init_detector(camera_index, dimensions, backend, frame_start, key_step, 0)
  File "C:\Users\********\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlendArMocap-main\src\main.py", line 115, in init_detector
    self.detector.stream = stream.Webcam(
  File "C:\Users\********\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlendArMocap-main\src\cgt_utils\stream.py", line 48, in __init__
    raise IOError("Cannot open webcam")

Cannot open webcam

Traceback (most recent call last):
  File "C:\Users\********\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlendArMocap-main\src\cgt_blender\interface\ui_operators.py", line 120, in execute
    self.detection_handler.init_detector(camera_index, dimensions, backend, frame_start, key_step, 0)
  File "C:\Users\********\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlendArMocap-main\src\main.py", line 115, in init_detector
    self.detector.stream = stream.Webcam(
  File "C:\Users\********\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\BlendArMocap-main\src\cgt_utils\stream.py", line 48, in __init__
    raise IOError("Cannot open webcam")
OSError: Cannot open webcam

**Comment by cgtinker** [comment]
Is you webcam properly connected? 
Set the webcam slot to 0 and make sure to have one webcam connected.

**Comment by xiaowen214** [comment]
Hi, thanks for the instant relpy.

I try the slot 0, still the same error.

I am using the laptop‘s camera, so the webcam should be the default setting?

**Comment by Tung-Vinh-Long** [comment]
> Hi, thanks for the instant relpy.
> 
> I try the slot 0, still the same error.
> 
> I am using the laptop‘s camera, so the webcam should be the default setting?

![image](https://user-images.githubusercontent.com/118338006/205642418-202c9be8-4cc8-4d81-b0c8-8397a9f14c87.png)
you should try switching back and forth between these 2 modes
